# action.yml
name: 'Black Duck Scan'
description: 'Run black duck scan'
inputs:
  input-args:
    description: 'input options'
    required: true
    default: '-h'
    type: string
runs:
  using: 'docker'
  # image: 'docker.repo.orl.eng.hitachivantara.com/security-scan/blackduck-dind'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-args }}
